#!/bin/sh
#
# pacup
# simple wrapper for updating arch system
#

abort()
{
  echo "aborting..."
  exit
}

frontPage()
{
    echo "Have you checked the front page?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) run; break;;
            No ) echo "You should really check the front page before upgrading."; abort;;
            * ) abort;;
        esac
    done
}

run()
{
  sudo aurman -Syu
}

if [ "$#" == 0 ]; then
  frontPage
else
  echo "Thanks, but not accepting arguments atm."
  abort
fi
